# Generated by Django 4.0.4 on 2022-05-02 03:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('country', models.CharField(max_length=56)),
                ('alpha_two_code', models.CharField(max_length=2)),
                ('web_pages', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('domains', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('state_province', models.TextField()),
            ],
        ),
    ]
