# Generated by Django 4.0.4 on 2022-05-04 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="university",
            name="state_province",
            field=models.TextField(blank=True),
        ),
    ]
